# Generated by Django 5.2.12 on 2026-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_management', '0002_jobrolemaster_company_and_more'),
        ('skill_management', '0005_employeeskillhistory_changed_by_change_reason'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeskillrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeskillrating',
            name='is_latest',
            field=models.BooleanField(default=True, help_text='True if this is the most recent rating for this employee/skill/type.'),
        ),
        migrations.AddIndex(
            model_name='employeeskillrating',
            index=models.Index(fields=['is_latest'], name='idx_skill_rating_is_latest'),
        ),
        migrations.AddConstraint(
            model_name='employeeskillrating',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('employee', 'skill', 'rating_type'), name='unique_latest_skill_rating'),
        ),
    ]
