# Generated by Django 5.2.12 on 2026-04-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrolemaster',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='org_management.companymaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobrolemaster',
            name='job_role_code',
            field=models.CharField(db_index=True, help_text='Unique short code for the designation.', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='jobrolemaster',
            unique_together={('job_role_code', 'company')},
        ),
    ]
