# Generated by Django 5.2.12 on 2026-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='', help_text='Frontend route to navigate to when the notification is clicked, e.g. /my-learning.', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(blank=True, default='', help_text='Model name of the source entity, e.g. UserCourseEnrollment.', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ENROLLMENT', 'Course Enrolled'), ('COMPLETION', 'Course Completed'), ('CERTIFICATE', 'Certificate Issued'), ('ASSESSMENT_RESULT', 'Assessment Result'), ('SKILL_UPGRADE', 'Skill Upgrade Proposal'), ('TNI_APPROVAL', 'Training Need Approved'), ('TNI_REJECTION', 'Training Need Rejected'), ('TNI_PENDING_REVIEW', 'Training Need Pending Review'), ('SKILL_RATING', 'Skill Rating Submitted'), ('RATING_CYCLE_OPEN', 'Rating Cycle Opened'), ('PLAN_PENDING_APPROVAL', 'Training Plan Pending Approval'), ('PLAN_APPROVED', 'Training Plan Approved'), ('PLAN_REJECTED', 'Training Plan Rejected'), ('SESSION_ENROLLED', 'Training Session Enrolled'), ('SESSION_REMINDER', 'Training Session Reminder'), ('COMPLIANCE_EXPIRY', 'Compliance Training Expiring'), ('COMPLIANCE_ALERT', 'Compliance Alert (Admin)'), ('NEW_ENROLLMENT', 'New Enrollment (Admin)'), ('TEAM_COMPLETION', 'Team Member Completed Course')], db_index=True, help_text='Machine-readable type used for icon/color rendering on the frontend.', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when is_read was set to True. Null while unread.', null=True),
        ),
    ]
