# Generated by Django 5.2.12 on 2026-05-06 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_engine', '0003_remove_useranswer_selected_option_and_more'),
        ('course_management', '0007_alter_courseparticipant_invited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmaster',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Optional: link to a course. Leave blank for standalone assessments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='course_management.coursemaster'),
        ),
    ]
