# Generated by Django 5.2.12 on 2026-05-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_engine', '0004_make_course_optional'),
        ('org_management', '0002_jobrolemaster_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRetakeGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', help_text='Optional reason for granting the retake.', max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(help_text='The assessment this grant applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='retake_grants', to='assessment_engine.assessmentmaster')),
                ('employee', models.ForeignKey(help_text='The learner who is granted the extra attempt.', on_delete=django.db.models.deletion.CASCADE, related_name='retake_grants', to='org_management.employeemaster')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Instructor or admin who issued the grant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_retake_grants', to='org_management.employeemaster')),
            ],
            options={
                'verbose_name': 'Assessment Retake Grant',
                'verbose_name_plural': 'Assessment Retake Grants',
                'db_table': 'asmt_retake_grant',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['assessment', 'employee'], name='idx_retake_grant_asmt_emp')],
            },
        ),
    ]
