# Generated by Django 5.2.12 on 2026-05-07 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_engine', '0005_add_retake_grant'),
        ('org_management', '0002_jobrolemaster_company_and_more'),
        ('skill_management', '0004_remove_employeeskillrating_uniq_employee_skill_rating_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Assessment Skill Mapping',
                'verbose_name_plural': 'Assessment Skill Mappings',
                'db_table': 'asmt_skill_mapping',
            },
        ),
        migrations.CreateModel(
            name='SkillUpgradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill Upgrade Proposal',
                'verbose_name_plural': 'Skill Upgrade Proposals',
                'db_table': 'asmt_skill_upgrade_proposal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestionmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessmentmaster',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=10, help_text='For DYNAMIC mode: how many questions to pick per attempt from the bank.'),
        ),
        migrations.AddField(
            model_name='assessmentmaster',
            name='question_selection_mode',
            field=models.CharField(choices=[('FIXED', 'Fixed — questions pre-mapped at assessment creation (course quizzes)'), ('DYNAMIC', 'Dynamic — questions selected from bank at attempt start (standalone)')], default='FIXED', help_text='FIXED: questions are pre-mapped at creation time (course quizzes). DYNAMIC: questions are selected from the bank at attempt start (standalone).', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentmaster',
            name='retake_cooldown_hours',
            field=models.PositiveIntegerField(default=0, help_text='Hours a learner must wait after a FAILED attempt before retaking. 0 = no cooldown. Only applies to standalone (DYNAMIC) assessments.'),
        ),
        migrations.AddField(
            model_name='assessmentquestionmapping',
            name='attempt',
            field=models.ForeignKey(blank=True, help_text='Set for DYNAMIC attempts. Null for FIXED (global) mappings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='assessment_engine.assessmentattempt'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='skill',
            field=models.ForeignKey(blank=True, help_text='Skill this question tests. Required for DYNAMIC assessments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='skill_management.skillmaster'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='skill_level',
            field=models.ForeignKey(blank=True, help_text='Minimum skill level this question targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='skill_management.skilllevelmaster'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['skill', 'skill_level'], name='idx_qbank_skill_level'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestionmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('attempt__isnull', True)), fields=('assessment', 'question'), name='uq_asmt_question_fixed'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestionmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('attempt__isnull', False)), fields=('attempt', 'question'), name='uq_asmt_question_dynamic'),
        ),
        migrations.AddField(
            model_name='assessmentskillmapping',
            name='assessment',
            field=models.ForeignKey(help_text='The standalone assessment this mapping belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='assessment_engine.assessmentmaster'),
        ),
        migrations.AddField(
            model_name='assessmentskillmapping',
            name='skill',
            field=models.ForeignKey(help_text='Skill that this assessment evaluates.', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mappings', to='skill_management.skillmaster'),
        ),
        migrations.AddField(
            model_name='assessmentskillmapping',
            name='skill_level',
            field=models.ForeignKey(help_text='Target proficiency level awarded on passing this assessment.', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_mappings', to='skill_management.skilllevelmaster'),
        ),
        migrations.AddField(
            model_name='skillupgradeproposal',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Employee who approved the upgrade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_skill_upgrades', to='org_management.employeemaster'),
        ),
        migrations.AddField(
            model_name='skillupgradeproposal',
            name='assessment_attempt',
            field=models.ForeignKey(help_text='The passing attempt that triggered this proposal.', on_delete=django.db.models.deletion.CASCADE, related_name='skill_upgrade_proposals', to='assessment_engine.assessmentattempt'),
        ),
        migrations.AddField(
            model_name='skillupgradeproposal',
            name='employee',
            field=models.ForeignKey(help_text='Learner whose skill level is proposed for upgrade.', on_delete=django.db.models.deletion.CASCADE, related_name='skill_upgrade_proposals', to='org_management.employeemaster'),
        ),
        migrations.AddField(
            model_name='skillupgradeproposal',
            name='proposed_level',
            field=models.ForeignKey(help_text='The skill level being proposed.', on_delete=django.db.models.deletion.PROTECT, related_name='upgrade_proposals', to='skill_management.skilllevelmaster'),
        ),
        migrations.AddField(
            model_name='skillupgradeproposal',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_proposals', to='skill_management.skillmaster'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentskillmapping',
            unique_together={('assessment', 'skill')},
        ),
        migrations.AddIndex(
            model_name='skillupgradeproposal',
            index=models.Index(fields=['employee', 'status'], name='idx_sup_employee_status'),
        ),
        migrations.AddIndex(
            model_name='skillupgradeproposal',
            index=models.Index(fields=['skill', 'status'], name='idx_sup_skill_status'),
        ),
    ]
