# Generated by Django 5.2.12 on 2026-05-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_engine', '0008_add_curated_question_selection_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmaster',
            name='question_selection_mode',
            field=models.CharField(choices=[('FIXED', 'Fixed — questions pre-mapped at assessment creation (course quizzes)'), ('DYNAMIC', 'Dynamic — questions selected from bank at attempt start (standalone)'), ('CURATED', 'Curated — manually selects questions from question bank (standalone)')], default='FIXED', help_text='FIXED: questions are pre-mapped at creation time (course quizzes). DYNAMIC: questions are selected from the bank at attempt start (standalone).', max_length=20),
        ),
    ]
