# Generated by Django 5.2.12 on 2026-05-18 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_engine', '0009_alter_assessmentmaster_question_selection_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmaster',
            name='certificate_validity_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days after passing before the certificate expires. Null = lifetime validity (no expiry date on the certificate).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
    ]
