# Generated by Django 5.2.12 on 2026-04-17 10:17

import apps.file_management.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_management', '0002_jobrolemaster_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.file_management.models.generate_file_path)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('PPT', 'Presentation (PPT/PPTX)'), ('VIDEO', 'Video'), ('SCORM', 'SCORM Package'), ('DOCUMENT', 'General Document'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='org_management.employeemaster')),
            ],
            options={
                'verbose_name_plural': 'File Registries',
                'db_table': 'file_registry',
                'ordering': ['-created_at'],
            },
        ),
    ]
