# Generated by Django 5.2.12 on 2026-06-01 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_fileregistry_converted_from_converting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScormPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorm_version', models.CharField(default='1.2', max_length=20)),
                ('launch_url', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('extracted_path', models.CharField(blank=True, default='', max_length=500)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('file_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_package', to='file_management.fileregistry')),
            ],
            options={
                'verbose_name': 'SCORM Package',
                'verbose_name_plural': 'SCORM Packages',
                'db_table': 'scorm_package',
            },
        ),
    ]
