# Generated by Django 5.2.12 on 2026-05-15 11:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_management', '0002_fileregistry_converted_from_converting_status'),
        ('org_management', '0002_jobrolemaster_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('certificate_type', models.CharField(choices=[('course', 'Course'), ('assessment', 'Assessment')], help_text='Whether this template is used for course or assessment certificates.', max_length=20)),
                ('blocks', models.JSONField(default=list, help_text='Ordered list of block objects defining the certificate layout.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cert_templates', to='org_management.employeemaster')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'db_table': 'cert_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID embedded in QR codes and verification URLs.', unique=True)),
                ('certificate_type', models.CharField(choices=[('course', 'Course'), ('assessment', 'Assessment')], max_length=20)),
                ('entity_id', models.PositiveIntegerField(help_text='PK of the enrollment (course) or attempt (assessment) that triggered issuance.')),
                ('completion_date', models.DateField(help_text='Date the course was completed or the assessment was passed.')),
                ('expiry_date', models.DateField(blank=True, help_text='Date after which the certificate is considered expired. Null = no expiry.', null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='')),
                ('employee', models.ForeignKey(help_text='Learner who earned this certificate.', on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='org_management.employeemaster')),
                ('pdf_file', models.ForeignKey(blank=True, help_text='Generated PDF stored in the file registry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_pdfs', to='file_management.fileregistry')),
                ('revoked_by', models.ForeignKey(blank=True, help_text='Admin who revoked this certificate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to='org_management.employeemaster')),
                ('template', models.ForeignKey(blank=True, help_text='Template used to generate this certificate. Null = default layout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='certificate_management.certificatetemplate')),
            ],
            options={
                'verbose_name': 'Issued Certificate',
                'verbose_name_plural': 'Issued Certificates',
                'db_table': 'cert_issued',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateRevocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revocation_log_entries', to='org_management.employeemaster')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revocation_logs', to='certificate_management.issuedcertificate')),
            ],
            options={
                'verbose_name': 'Certificate Revocation Log',
                'verbose_name_plural': 'Certificate Revocation Logs',
                'db_table': 'cert_revocation_log',
                'ordering': ['-revoked_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('course', 'Course'), ('assessment', 'Assessment')], help_text='Whether these settings apply to a course or an assessment.', max_length=20)),
                ('entity_id', models.PositiveIntegerField(help_text='PK of the course or assessment this setting belongs to.')),
                ('use_default_template', models.BooleanField(default=True, help_text='When True, the system default layout is used instead of a custom template.')),
                ('expiry_duration_days', models.PositiveIntegerField(blank=True, help_text='Days after completion_date before the certificate expires. Null = no expiry.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('template', models.ForeignKey(blank=True, help_text='Custom template to use. Null when use_default_template=True.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_usages', to='certificate_management.certificatetemplate')),
            ],
            options={
                'verbose_name': 'Certificate Settings',
                'verbose_name_plural': 'Certificate Settings',
                'db_table': 'cert_settings',
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
        migrations.AddIndex(
            model_name='issuedcertificate',
            index=models.Index(fields=['employee', 'certificate_type'], name='idx_cert_emp_type'),
        ),
        migrations.AddIndex(
            model_name='issuedcertificate',
            index=models.Index(fields=['certificate_id'], name='idx_cert_uuid'),
        ),
        migrations.AddIndex(
            model_name='issuedcertificate',
            index=models.Index(fields=['entity_id', 'certificate_type'], name='idx_cert_entity'),
        ),
    ]
