# Generated by Django 5.2.12 on 2026-05-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='issuedcertificate',
            name='template',
        ),
        migrations.AddField(
            model_name='issuedcertificate',
            name='course_or_assessment_name',
            field=models.CharField(default='', help_text='Human-readable name of the course or assessment, stored at issuance time.', max_length=255),
        ),
        migrations.AlterField(
            model_name='issuedcertificate',
            name='entity_id',
            field=models.CharField(help_text='PK of the enrollment (course) or attempt (assessment) that triggered issuance. Stored as a string to accommodate both integer and UUID PKs.', max_length=100),
        ),
        migrations.AlterField(
            model_name='issuedcertificate',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date after which the certificate is considered expired. Null = lifetime validity.', null=True),
        ),
        migrations.DeleteModel(
            name='CertificateSettings',
        ),
        migrations.DeleteModel(
            name='CertificateTemplate',
        ),
    ]
