# Generated by Django 5.2.12 on 2026-05-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_management', '0002_jobrolemaster_company_and_more'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Permission Group',
                'verbose_name_plural': 'Company Permission Groups',
                'db_table': 'rbac_company_permission_group',
            },
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Owning company for custom roles. Null for system roles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_roles', to='org_management.companymaster'),
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='True for platform-defined roles that cannot be edited or deleted by company admins.'),
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='role_code',
            field=models.CharField(db_index=True, help_text='Short code for the role. Unique globally for system roles; unique per company for custom roles.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='rolemaster',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('role_code', 'company'), name='uq_role_code_per_company'),
        ),
        migrations.AddField(
            model_name='companypermissiongroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_groups', to='org_management.companymaster'),
        ),
        migrations.AddField(
            model_name='companypermissiongroup',
            name='permission_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_grants', to='rbac.permissiongroupmaster'),
        ),
        migrations.AddIndex(
            model_name='companypermissiongroup',
            index=models.Index(fields=['company'], name='idx_cpg_company_id'),
        ),
        migrations.AddIndex(
            model_name='companypermissiongroup',
            index=models.Index(fields=['permission_group'], name='idx_cpg_group_id'),
        ),
        migrations.AlterUniqueTogether(
            name='companypermissiongroup',
            unique_together={('company', 'permission_group')},
        ),
    ]
