# Generated by Django 5.2.12 on 2026-04-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='file_ref',
            field=models.ForeignKey(blank=True, help_text='Link to the physical file in the registry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_usages', to='file_management.fileregistry'),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='file_ref',
            field=models.ForeignKey(blank=True, help_text='Link to the physical file for this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_usages', to='file_management.fileregistry'),
        ),
    ]
