# Generated by Django 5.2.12 on 2026-05-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0007_alter_courseparticipant_invited_by_and_more'),
        ('learning_progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning_progress.usercourseenrollment')),
                ('lesson', models.ForeignKey(blank=True, help_text='Lesson this note belongs to. Null means a course-level note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='course_management.courselesson')),
            ],
            options={
                'verbose_name': 'Course Note',
                'verbose_name_plural': 'Course Notes',
                'db_table': 'course_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment'], name='idx_course_note_enrollment')],
            },
        ),
    ]
