# Generated by Django 5.2.12 on 2026-05-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0008_add_course_note_model'),
        ('org_management', '0002_jobrolemaster_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTrainerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_external', models.BooleanField(default=False, help_text='True when the trainer is not a company employee.')),
                ('trainer_name', models.CharField(blank=True, default='', help_text='Full name — required when is_external=True.', max_length=200)),
                ('trainer_email', models.EmailField(blank=True, default='', help_text='Contact email — required when is_external=True.', max_length=254)),
                ('trainer_contact', models.CharField(blank=True, default='', help_text='Phone / contact number.', max_length=30)),
                ('trainer_info', models.TextField(blank=True, default='', help_text='Short bio or additional information about the trainer.')),
                ('is_primary', models.BooleanField(default=False, help_text='Marks the lead trainer for the course.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='course_management.coursemaster')),
                ('employee', models.ForeignKey(blank=True, help_text='Set when is_external=False.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_assignments', to='org_management.employeemaster')),
            ],
            options={
                'verbose_name': 'Course Trainer',
                'verbose_name_plural': 'Course Trainers',
                'db_table': 'course_trainer_map',
                'indexes': [models.Index(fields=['course'], name='idx_crs_trainer_course')],
            },
        ),
    ]
