# Generated by Django 5.2.12 on 2026-05-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0009_add_course_trainer_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemaster',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='If True, learners must complete this course. Mandatory courses remain accessible after end_date (soft lock). Optional courses are locked once end_date passes.'),
        ),
    ]
