# Generated by Django 5.2.12 on 2026-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0011_coursemaster_certificate_validity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('PPT', 'PPT'), ('DOCUMENT', 'Document'), ('LINK', 'External Link'), ('QUIZ', 'Quiz'), ('SCORM', 'SCORM Package')], default='VIDEO', max_length=50),
        ),
    ]
