# Generated by Django 5.2.12 on 2026-04-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_management', '0001_initial'),
        ('skill_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SELF', 'Self Assessment'), ('MANAGER', 'Manager Evaluation'), ('SKILL_GAP', 'Skill Gap Detection'), ('COMPLIANCE', 'Compliance Requirement'), ('SYSTEM', 'System Generated')], default='SKILL_GAP', help_text='Origin of the training need identification.', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PLANNED', 'Planned'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50)),
                ('notes', models.CharField(blank=True, default='', help_text='Additional context regarding the identified need.', max_length=255)),
                ('identified_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the need was first recorded.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete switch.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee who requires training.', on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to='org_management.employeemaster')),
                ('skill', models.ForeignKey(help_text='Specific skill required.', on_delete=django.db.models.deletion.CASCADE, related_name='tni_entries', to='skill_management.skillmaster')),
            ],
            options={
                'verbose_name': 'Training Need',
                'verbose_name_plural': 'Training Needs',
                'db_table': 'tni_training_need',
                'ordering': ['-identified_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingNeedApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('comments', models.CharField(blank=True, default='', help_text='Remarks by the approver.', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when the action was finalized.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_tni_approvals', to='org_management.employeemaster')),
                ('training_need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tni_management.trainingneed')),
            ],
            options={
                'verbose_name': 'Training Need Approval',
                'verbose_name_plural': 'Training Need Approvals',
                'db_table': 'tni_training_need_approval',
            },
        ),
        migrations.CreateModel(
            name='TrainingNeedCourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField(help_text='Reference to future CourseMaster(id).')),
                ('recommendation_reason', models.CharField(blank=True, default='', help_text='Why this course was chosen to address the need.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to='tni_management.trainingneed')),
            ],
            options={
                'verbose_name': 'TNI Course Recommendation',
                'verbose_name_plural': 'TNI Course Recommendations',
                'db_table': 'tni_training_need_course_recommendation',
            },
        ),
        migrations.CreateModel(
            name='ComplianceTrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField(help_text='Foreign Key to future CourseMaster(id).')),
                ('mandatory', models.BooleanField(default=True, help_text='Whether this training is strictly required for compliance.')),
                ('validity_days', models.IntegerField(help_text='Number of days before the certification/training expires.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_role', models.ForeignKey(help_text='Role the mandatory training applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_requirements', to='org_management.jobrolemaster')),
            ],
            options={
                'verbose_name': 'Compliance Training Requirement',
                'verbose_name_plural': 'Compliance Training Requirements',
                'db_table': 'tni_compliance_training_requirement',
                'indexes': [models.Index(fields=['job_role'], name='idx_compliance_role_id'), models.Index(fields=['course_id'], name='idx_compliance_course_id')],
            },
        ),
        migrations.CreateModel(
            name='SkillGapSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_value', models.IntegerField(help_text='Numerical difference between required and current level ranks.')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_level', models.ForeignKey(help_text="The employee's proficiency level at the time of detection.", on_delete=django.db.models.deletion.PROTECT, related_name='gap_current_snapshots', to='skill_management.skilllevelmaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_snapshots', to='org_management.employeemaster')),
                ('required_level', models.ForeignKey(help_text='The proficiency level required by the job role.', on_delete=django.db.models.deletion.PROTECT, related_name='gap_required_snapshots', to='skill_management.skilllevelmaster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_management.skillmaster')),
            ],
            options={
                'verbose_name': 'Skill Gap Snapshot',
                'verbose_name_plural': 'Skill Gap Snapshots',
                'db_table': 'tni_skill_gap_snapshot',
                'indexes': [models.Index(fields=['employee'], name='idx_skill_gap_employee_id'), models.Index(fields=['skill'], name='idx_skill_gap_skill_id')],
            },
        ),
        migrations.CreateModel(
            name='TNIAggregatedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_training_needs', models.IntegerField(default=0)),
                ('high_priority_needs', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tni_analytics', to='org_management.departmentmaster')),
            ],
            options={
                'verbose_name': 'TNI Aggregated Analysis',
                'verbose_name_plural': 'TNI Aggregated Analyses',
                'db_table': 'tni_aggregated_analysis',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['department'], name='idx_tni_analysis_dept_id')],
            },
        ),
        migrations.AddIndex(
            model_name='trainingneed',
            index=models.Index(fields=['employee'], name='idx_tni_need_employee_id'),
        ),
        migrations.AddIndex(
            model_name='trainingneed',
            index=models.Index(fields=['skill'], name='idx_tni_need_skill_id'),
        ),
        migrations.AddIndex(
            model_name='trainingneed',
            index=models.Index(fields=['status'], name='idx_tni_need_status'),
        ),
        migrations.AddIndex(
            model_name='trainingneedapproval',
            index=models.Index(fields=['training_need'], name='idx_tni_approval_need_id'),
        ),
        migrations.AddIndex(
            model_name='trainingneedapproval',
            index=models.Index(fields=['approver'], name='idx_tni_approval_approver_id'),
        ),
        migrations.AddIndex(
            model_name='trainingneedcourserecommendation',
            index=models.Index(fields=['training_need'], name='idx_tni_course_need_id'),
        ),
        migrations.AddIndex(
            model_name='trainingneedcourserecommendation',
            index=models.Index(fields=['course_id'], name='idx_tni_course_course_id'),
        ),
    ]
