# Generated by Django 5.2.12 on 2026-05-25 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_management', '0002_jobrolemaster_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGamificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Company-level toggle; also requires global feature flag gamification_enabled.')),
                ('inactive_leaderboard_days', models.PositiveSmallIntegerField(default=90)),
                ('learning_streak_min_seconds', models.PositiveIntegerField(default=300)),
                ('mandatory_course_xp_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('retake_xp_percent_2nd', models.PositiveSmallIntegerField(default=40)),
                ('retake_xp_percent_3rd_plus', models.PositiveSmallIntegerField(default=20)),
                ('streak_daily_xp_bonus', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_config', to='org_management.companymaster')),
            ],
            options={
                'verbose_name': 'Company Gamification Config',
                'verbose_name_plural': 'Company Gamification Configs',
                'db_table': 'gamification_company_config',
            },
        ),
    ]
