# Generated by Django 5.2.12 on 2026-05-25 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        ('org_management', '0002_jobrolemaster_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygamificationconfig',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AwardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('base_points', models.PositiveIntegerField()),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamification_award_rules', to='org_management.companymaster')),
            ],
            options={
                'db_table': 'gamification_award_rule',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('code', 'company'), name='uniq_gamification_award_rule_code_company')],
            },
        ),
        migrations.CreateModel(
            name='PointBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_xp', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_point_balances', to='org_management.companymaster')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_balance', to='org_management.employeemaster')),
            ],
            options={
                'db_table': 'gamification_point_balance',
                'indexes': [models.Index(fields=['company', '-lifetime_xp'], name='idx_gami_balance_co_xp')],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('rule_code', models.CharField(db_index=True, max_length=64)),
                ('source_type', models.CharField(db_index=True, max_length=64)),
                ('source_id', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='org_management.companymaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='org_management.employeemaster')),
            ],
            options={
                'db_table': 'gamification_point_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', '-created_at'], name='idx_gami_pt_emp_created'), models.Index(fields=['company', '-created_at'], name='idx_gami_pt_co_created')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'rule_code', 'source_type', 'source_id'), name='uniq_gamification_point_award')],
            },
        ),
    ]
