# Generated by Django 5.2.12 on 2026-05-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_companygamificationconfig_is_enabled_awardrule_and_more'),
        ('org_management', '0002_jobrolemaster_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygamificationconfig',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Company-level toggle; also requires global feature flag gamification_enabled.'),
        ),
        migrations.CreateModel(
            name='EmployeeStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_type', models.CharField(db_index=True, max_length=32)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_streaks', to='org_management.companymaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_streaks', to='org_management.employeemaster')),
            ],
            options={
                'db_table': 'gamification_employee_streak',
                'constraints': [models.UniqueConstraint(fields=('employee', 'streak_type'), name='uniq_gamification_employee_streak')],
            },
        ),
        migrations.CreateModel(
            name='StreakActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_type', models.CharField(db_index=True, max_length=32)),
                ('activity_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_activity_logs', to='org_management.companymaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_activity_logs', to='org_management.employeemaster')),
            ],
            options={
                'db_table': 'gamification_streak_activity_log',
                'ordering': ['-activity_date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'streak_type', 'activity_date'), name='uniq_gamification_streak_activity_day')],
            },
        ),
    ]
