# Generated by Django 5.2.12 on 2026-05-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_alter_companygamificationconfig_is_enabled_and_more'),
        ('org_management', '0002_jobrolemaster_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('learning', 'Learning'), ('compliance', 'Compliance'), ('assessment', 'Assessment'), ('skills', 'Skills'), ('certificates', 'Certificates'), ('streak', 'Streak'), ('milestone', 'Milestone')], db_index=True, max_length=32)),
                ('criteria_type', models.CharField(db_index=True, max_length=64)),
                ('criteria_value', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('icon_key', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gamification_badge_definition',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_awards', to='gamification.badgedefinition')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_badges', to='org_management.companymaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='org_management.employeemaster')),
            ],
            options={
                'db_table': 'gamification_employee_badge',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['employee', '-earned_at'], name='idx_gami_badge_emp_earned')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'badge'), name='uniq_gamification_employee_badge')],
            },
        ),
    ]
