# Generated by Django 5.2.12 on 2026-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseenrollment',
            name='extended_due_date',
            field=models.DateField(blank=True, help_text='Admin-set per-learner deadline override. When set, this takes precedence over course.end_date for overdue calculations.', null=True),
        ),
        migrations.AlterField(
            model_name='usercourseenrollment',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('OVERDUE', 'Overdue')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('OVERDUE', 'Overdue')], default='NOT_STARTED', max_length=50),
        ),
    ]
