# Generated by Django 5.2.12 on 2026-06-01 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0012_alter_coursecontent_content_type'),
        ('learning_progress', '0002_add_extended_due_date_and_overdue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSCORMProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_status', models.CharField(default='not attempted', max_length=20)),
                ('success_status', models.CharField(blank=True, default='', max_length=10)),
                ('lesson_location', models.CharField(blank=True, default='', max_length=255)),
                ('score_raw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('score_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('score_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('score_scaled', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('suspend_data', models.TextField(blank=True, default='')),
                ('scorm_variables', models.JSONField(default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('first_accessed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scorm_progress', to='course_management.coursecontent')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_progress', to='learning_progress.usercourseenrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scorm_lesson_progress', to='course_management.courselesson')),
            ],
            options={
                'verbose_name': 'User SCORM Progress',
                'verbose_name_plural': 'User SCORM Progress Records',
                'db_table': 'lp_user_scorm_progress',
                'indexes': [models.Index(fields=['enrollment', 'content'], name='idx_scorm_enroll_content')],
                'unique_together': {('enrollment', 'content')},
            },
        ),
    ]
